# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_options',
            field=models.CharField(choices=[('pagseguro', 'PagSeguro'), ('paypal', 'Paypal'), ('deposit', 'Depósito')], default='deposit', max_length=10, verbose_name='Opção de Pagamento'),
        ),
    ]
